//
//  DebugString.swift
//  imageOCR
//
//  Created by 杨光 on 2020/11/7.
//  Copyright © 2020 Ivan Nesterenko. All rights reserved.
//

import Foundation


struct DebugString{
    static var jsonStringCoffee: String = "{\"log_id\":3368777552733262400,\"coffee_result_num\":2,\"words_result\":[{\"location\":{\"width\":1887,\"top\":925,\"height\":267,\"left\":2320},\"base64\":\"\",\"url\":\"http://buddyoj.com/VIS/AR/Coffee/coffee001.jpg\",\"fragrance\":\"pleasant\",\"aroma\":\"Too light\",\"acidity\":\"Slightly acidic\",\"body\":\"rich\",\"aftertaste\":\"peaceful\",\"flavor\":\"Soft and smooth\",\"balance\":\"Not full enough\",\"score\":0.68,\"remark\":\"Flavor, bitterness, sweetness, astringency and sour taste.\",\"desbase64\":\"\",\"desurl\":\"http://buddyoj.com/VIS/AR/Coffee/coffeedes001.jpg\"},{\"location\":{\"width\":329,\"top\":446,\"left\":1280,\"height\":173},\"url\":\"http://buddyoj.com/VIS/AR/Coffee/coffee002.jpg\",\"fragrance\":\"pleasant\",\"aroma\":\"Too light\",\"acidity\":\"Slightly acidic\",\"body\":\"rich\",\"aftertaste\":\"peaceful\",\"flavor\":\"Soft and smooth\",\"balance\":\"Not full enough\",\"score\":0.76,\"remark\":\"Flavor, bitterness, sweetness, astringency and sour taste.\",\"desurl\":\"http://buddyoj.com/VIS/AR/Coffee/coffeedes002.jpg\"}]}";
    static var jsonString: String =
        "{\"log_id\":3368777552734162400,\"books_result_num\":2,\"words_result\":[{\"part\":[{\"location\":{\"width\":39,\"top\":66,\"left\":180,\"height\":17},\"words\":\"Free Will\",\"type\":\"name\",\"base64\":\"this part photo base64code\",\"url\":\"http://buddyoj.com/VIS/AR/Book/books002.jpg\"},{\"location\":{\"width\":39,\"top\":66,\"left\":180,\"height\":17},\"words\":\"Sam Harris\",\"type\":\"author\",\"base64\":\"this part photo base64code\",\"url\":\"http://buddyoj.com/VIS/AR/Book/books002.jpg\"},{\"location\":{\"width\":39,\"top\":66,\"left\":180,\"height\":17},\"words\":\"Nanjing University\",\"type\":\"publisher\",\"base64\":\"this part photo base64code\",\"url\":\"http://buddyoj.com/VIS/AR/Book/books002.jpg\"}],\"location\":{\"top\":1839,\"left\":1695,\"width\":1465,\"height\":185},\"base64\":\"this book photo base64code\",\"url\":\"http://buddyoj.com/VIS/AR/Book/books002.jpg\",\"title\":\"Make America great again\",\"author\":\"Yang\",\"publisher\":\"America\",\"relatebooks\":\"Go with wind\",\"score\":0.6,\"remark\":\"good author, good book. People who can hear this book are very handsome.\"},{\"part\":[{\"location\":{\"width\":39,\"top\":66,\"left\":180,\"height\":17},\"words\":\"More Than Good Intensions\",\"type\":\"name\",\"base64\":\"this part photo base64code\",\"url\":\"http://buddyoj.com/VIS/AR/Book/books002.jpg\"},{\"location\":{\"width\":39,\"top\":66,\"left\":180,\"height\":17},\"words\":\"Dean Karlan\",\"type\":\"author\",\"base64\":\"this part photo base64code\",\"url\":\"http://buddyoj.com/VIS/AR/Book/books002.jpg\"},{\"location\":{\"width\":39,\"top\":66,\"left\":180,\"height\":17},\"words\":\"Nanjing Normal University\",\"type\":\"publisher\",\"base64\":\"this part photo base64code\",\"url\":\"http://buddyoj.com/VIS/AR/Book/books002.jpg\"}],\"location\":{\"top\":2039,\"left\":1695,\"width\":1465,\"height\":185},\"base64\":\"this book photo base64code\",\"url\":\"http://buddyoj.com/VIS/AR/Book/books002.jpg\",\"title\":\"Make China great again\",\"author\":\"Trump\",\"publisher\":\"China\",\"relatebooks\":\"Go with wind\",\"score\":0.8,\"remark\":\"good author, good book. People who can hear this book are very handsome.\"}]}"

}
